apiVersion: apps/v1
kind: Deployment

metadata:
  name: patins
  labels:
    app: patins

spec:
  replicas: 1
  selector:
    matchLabels:
      app: patins

  template:
    metadata:
      labels:
        app: patins

    spec:
      containers:
      - name: patinsapi
        image: 433581887735.dkr.ecr.ap-south-1.amazonaws.com/patins:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
          - name: MONGO_HOST
            value: mongo
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_URI_CONNECT
            value: mongodb://mongo:27017
